### ISSUE TITLE
Fails to compile with Veloren

### ISSUE THREAD

**Issue by Songtronix** [ldesgoui/discord_game_sdk#52]
**NOTE:** On it's own it compiles just fine. This is a tracking issue to correlate where the issue might come from and a reference for library authors.

Error:
```Rust
error: failed to run custom build command for `discord_game_sdk_sys v0.5.0-alpha.1`
Caused by:
  process didn't exit successfully: `/home/songtronix/Desktop/Repositories/veloren/veloren/target/debug/build/discord_game_sdk_sys-252a84791f3db113/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-env-changed=DISCORD_GAME_SDK_PATH
--- stderr
thread 'main' panicked at 'a `libclang` shared library is not loaded on this thread', src/libcore/option.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::option::expect_failed
             at src/libcore/option.rs:1188
  14: clang_sys::clang_createIndex
  15: bindgen::ir::context::BindgenContext::new
  16: bindgen::Builder::generate
  17: build_script_build::main
  18: std::rt::lang_start::{{closure}}
  19: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  20: std::panicking::try::do_call
             at src/libstd/panicking.rs:292
  21: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:78
  22: std::panicking::try
             at src/libstd/panicking.rs:270
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: main
  26: __libc_start_main
  27: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

The error mentions threads and as such I limited compiling dependencies with `-j 1` but the error still persists.

*OS*: Arch Linux
*Clang Info*:
```
clang version 9.0.0 (tags/RELEASE_900/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-pc-linux-gnu/9.2.0
Found candidate GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0
Found candidate GCC installation: /usr/lib64/gcc/x86_64-pc-linux-gnu/9.2.0
Selected GCC installation: /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/9.2.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Selected multilib: .;@m64
```

How to reproduce:
Checkout ``songtronix/improve-discord`` on the veloren repository and compile with ``cargo run --features "discord" --manifest-path voxygen/Cargo.toml``. Make sure to set DISCORD_GAME_SDK_PATH to point to a valid download of the sdk.

**Comment by Songtronix** [comment]
Pinned down to first alpha version. *0.4.1* works fine but *0.5.0-alpha.1* fails.

**Comment by Songtronix** [comment]
This can be fixed by enabling the default features of `bindgen`. However it does throw this now:
```
warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable
```
which probably is easily mitigated by installing llvm-config (though introduces a dependency).

**Comment by ldesgoui** [comment]
Should be fixed with https://github.com/ldesgoui/discord_game_sdk/commit/2c8eef166a9c97a04eba067d7fd8b99d62002ba9 / discord_game_sdk_sys 0.5.0-alpha.2

**Comment by Songtronix** [comment]
I will close this once I've tested that it works ^^
